### ISSUE TITLE
Table not showing

### ISSUE THREAD

**Issue by ewosl** [kaarthik108/snowChat#3]
Hi!

Are you supposed to first select a table from the side bar from the database you specify in secrets.toml file? Because for me, the options are still the default ones 
![image](https://github.com/kaarthik108/snowChat/assets/134050474/b5c83db9-56d8-44db-be8b-076ae88ce8e0)
And even if I query the default tables I don't get a table, and the code generated is not formatted like in the demo app:
![image](https://github.com/kaarthik108/snowChat/assets/134050474/6dd44b00-4b4e-4350-9f4d-b6947c242004)

What could've been wrong? Thanks so much!

**Comment by kaarthik108** [comment]
This has been fixed, I think it was timing out earlier. 👍
