### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by kshitijyad** [kaarthik108/snowChat#7]
Hey buddy! Amazing work. Kudos to this project.

Could you provide work flow information on how this is working (how you are stiching various things together here)? 
Do you have a medium article explaining the logic of this project?

Also, Why are you using Supabase?
Really waiting to hear from you on this.

**Comment by kaarthik108** [comment]
Just published recently if you want to have a look at how snowchat works - https://blog.streamlit.io/snowchat-leveraging-openais-gpt-for-sql-queries/

Supabase is for storing the vector embeddings. (Also it is free to use)
