### ISSUE TITLE
Best way to generate schema docs from snowflake

### ISSUE THREAD

**Issue by esanketkulkarni** [kaarthik108/snowChat#8]
> Make you're schemas and store them in docs folder that matches you're database.

In above mentioned step, are we expected manually get(copy) the schema definitions of **all** tables and views from the database or there is an automated or quicker way to download all schemas with a single click from snowflake?

**Comment by kaarthik108** [comment]
Hi @esanketkulkarni , I have made another project where this step is automated. The code for it is here for your reference 
https://github.com/kaarthik108/snowBrain/blob/main/embed/snowflake_ddl_fetcher.py
