### ISSUE TITLE
Chain import issue

### ISSUE THREAD

**Issue by sureshsinganamala** [kaarthik108/snowChat#9]
Hi @kaarthik108 @esanketkulkarni, I have followed same steps and able to run the app but getting following error. Can any one please suggest me how to fix?

![image](https://github.com/kaarthik108/snowChat/assets/140687595/0ce38897-f53c-433c-ac4c-a1a5d90d3fb2)

**Comment by esanketkulkarni** [comment]
I am not sure how it's working for @kaarthik108 , but can you make below change and try if it works?
```
'- from chain import load_chain
+ from langchain.chains import load_chain`
```

**Comment by esanketkulkarni** [comment]
Can you confirm if you have `chain.py` in same level as` main.py`? and `chain.py` has the function `load_chain`?

**Comment by sureshsinganamala** [comment]
Hi @esanketkulkarni,  the file locations are proper and you can see it in below images.

![image](https://github.com/kaarthik108/snowChat/assets/140687595/8d29ecbb-a9c7-4bee-8ab3-9cbee26c6922)
![image](https://github.com/kaarthik108/snowChat/assets/140687595/d85fe952-4026-478c-b458-60266d098308)

**Comment by sureshsinganamala** [comment]
If I copy chain.py code into main.py then its working for me. Is there any loading file issue?

**Comment by esanketkulkarni** [comment]
May I know how you are starting or running main.py? Pycharm or using CLI?
